name: 'master_build'
on:
  push:
    branches: [ master ]

env:
  MAVEN_OPTS: -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn

jobs:
  build_job:
    runs-on: ubuntu-latest
    name: Build & Test Microservice
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: 21
      - uses: s4u/maven-settings-action@v2.8.0
        with:
          servers: |
            [{
              "id": "sonatype-nexus-snapshots",
              "username": "${{ secrets.OSS_USERNAME }}",
              "password": "${{ secrets.OSS_PASSWORD }}"
            }]
      - name: Build
        run: >
          ./mvnw deploy
          -Dci.buildNumber=$GITHUB_RUN_NUMBER
          -U -B $MAVEN_OPTS
